<?php
session_start();
include('../includes/Database.php');
$db = new Database();
$id_trainee = $_GET['id_trainee'];
$id_stage = $_GET['id_stage'];
$db->select('trainees','fname,lname,cin,email,institute',null,'id='.$id_trainee);
$trainee = $db->getResult()[0];
$db->select('certificates_templates','template_content',null,'state=1');
$certif_content = $db->getResult()[0]['template_content'];
$db->select('attribution_internship','*',null,'id='.$id_stage);
$stage = $db->getResult()[0];
$db->select('internship_types','*',null,'id='.$stage['id_type']);
$type = 'Stage '.$db->getResult()[0]['type'];
$db->select('scolar_establishment','*',null,'id='.$trainee['institute']);
$etablissement= $db->getResult()[0]['name'];
$db->select('config_certificate','*');
$config_certificate= $db->getResult()[0];
$certif_content = str_replace('t.lname',$trainee['lname'],$certif_content);
$certif_content = str_replace('t.fname',$trainee['fname'],$certif_content);
$certif_content = str_replace('t.cin',$trainee['cin'],$certif_content);
$certif_content = str_replace('t.email',$trainee['email'],$certif_content);
$certif_content = htmlspecialchars_decode($certif_content);
$certif_content = str_replace('\"','"',$certif_content);
$certif_content = str_replace("\&#039;","'",$certif_content);
$certif_content = str_replace("@currentdate",date('d-m-Y'),$certif_content);
$certif_content = str_replace('s.date_start',date('d-m-Y',strtotime($stage['date_start'])),$certif_content);
$certif_content = str_replace('s.date_end',date('d-m-Y',strtotime($stage['date_end'])),$certif_content);
$certif_content = str_replace('i.type',$type,$certif_content);
$certif_content = str_replace('sc.name',$etablissement,$certif_content);
$certif_content = str_replace('div.fname',$config_certificate['div_fname'],$certif_content);
$certif_content = str_replace('div.lname',$config_certificate['div_lname'],$certif_content);
$certif_content = str_replace('div.function',$config_certificate['div_post'],$certif_content);
require '../vendor/autoload.php';
use Spipu\Html2Pdf\Html2Pdf;
ob_start();
include dirname(__FILE__).'/certif1.php';
$html2pdf = new Html2Pdf('L', 'A4', 'fr',true,'UTF-8');
$content = ob_get_clean();
$html2pdf->writeHTML($content);
$response = [];
$response['file']=$html2pdf->output('test.pdf','E');
echo json_encode($response);
